version: "3.8"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
    volumes:
      - ./api-gateway/src:/app/src

  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
    volumes:
      - ./discovery-service/src:/app/src


  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: jdbc:postgresql://user-db:5432/user_service_db
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
      - user-db
    volumes:
      - ./user-service/src:/app/src

  ticket-service:
    build: ./ticket-service
    ports:
      - "8082:8082"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: jdbc:postgresql://ticket-db:5432/ticket_service_db
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
      - ticket-db
    volumes:
      - ./ticket-service/src:/app/src

  technician-service:
    build: ./technician-service
    ports:
      - "8083:8083"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: jdbc:postgresql://technician-db:5432/technician_service_db
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
      - technician-db
    volumes:
      - ./technician-service/src:/app/src

  user-db:
    image: postgres:13
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data

  ticket-db:
    image: postgres:13
    environment:
      POSTGRES_DB: ticket_service_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ticket_db_data:/var/lib/postgresql/data

  technician-db:
    image: postgres:13
    environment:
      POSTGRES_DB: technician_service_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - technician_db_data:/var/lib/postgresql/data

volumes:
  user_db_data:
  ticket_db_data:
  technician_db_data: