version: "3.8"

services:
  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: jdbc:postgresql://postgres:5432/user_service_db
    depends_on:
      - discovery-service
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: